sbi_dict = {}

# TS29502_Nsmf_PDUSession.yaml
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/sm-contexts', 'post')] = {'interface':'N11','dir':'0','msgType':'50000','response':{'201':'successful creation of an SM context','307':'temporary redirect','308':'permanent redirect','400':'unsuccessful creation of an SM context - bad request','403':'unsuccessful creation of an SM context - forbidden','404':'unsuccessful creation of an SM context - not found','500':'unsuccessful creation of an SM context - internal server error','503':'unsuccessful creation of an SM context - service unavailable','504':'unsuccessful creation of an SM context - gateway timeout',},'callbacks':{('smContextStatusNotification', '{$request.body#/smContextStatusUri}','post'): {'interface':'N11','dir':'1','msgType':'50002','response':{'204':'successful notification','307':'temporary redirect',}},}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/sm-contexts/{smContextRef}/retrieve', 'post')] = {'interface':'N11','dir':'0','msgType':'50004','response':{'200':'successful retrieval of an SM context',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/sm-contexts/{smContextRef}/modify', 'post')] = {'interface':'N11','dir':'0','msgType':'50006','response':{'200':'successful update of an SM context with content in the response','204':'successful update of an SM context without content in the response','400':'unsuccessful update of an SM context - bad request','403':'unsuccessful update of an SM context - forbidden','404':'unsuccessful update of an SM context - not found','500':'unsuccessful update of an SM context - Internal server error','503':'unsuccessful update of an SM context - Service Unavailable',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/sm-contexts/{smContextRef}/release', 'post')] = {'interface':'N11','dir':'0','msgType':'50008','response':{'204':'successful release of an SM context without content in the response',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/pdu-sessions', 'post')] = {'interface':'N11','dir':'0','msgType':'50010','response':{'201':'successful creation of a PDU session','307':'temporary redirect','308':'permanent redirect',},'callbacks':{('statusNotification', '{$request.body#/vsmfPduSessionUri}','post'): {'interface':'N11','dir':'1','msgType':'50012','response':{'204':'successful notificationof the status change',}},('statusNotification-ismf', '{$request.body#/ismfPduSessionUri}','post'): {'interface':'N11','dir':'1','msgType':'50014','response':{'204':'successful notificationof the status change',}},('update', '{$request.body#/vsmfPduSessionUri}/modify','post'): {'interface':'N11','dir':'1','msgType':'50016','response':{'204':'successful update of a PDU session without content in the response',}},('update-ismf', '{$request.body#/ismfPduSessionUri}/modify','post'): {'interface':'N11','dir':'1','msgType':'50018','response':{'204':'successful update of a PDU session without content in the response',}},}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/pdu-sessions/{pduSessionRef}/modify', 'post')] = {'interface':'N11','dir':'0','msgType':'50020','response':{'200':'successful update of a PDU session with content in the response','204':'successful update of a PDU session without content in the response',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf-pdusession/v1', '/pdu-sessions/{pduSessionRef}/release', 'post')] = {'interface':'N11','dir':'0','msgType':'50022','response':{'204':'successful release of a PDU session',},'callbacks':{}}

# TS29503_Nudm_SDM.yaml
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}', 'get')] = {'interface':'N8','dir':'0','msgType':'50026','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/nssai', 'get')] = {'interface':'N8','dir':'0','msgType':'50028','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/am-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50030','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/smf-select-data', 'get')] = {'interface':'N10','dir':'1','msgType':'50032','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/ue-context-in-smf-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50034','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/ue-context-in-smsf-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50036','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/trace-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50038','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sm-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50040','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sms-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50042','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sms-mng-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50044','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sdm-subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50046','response':{'201':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{('datachangeNotification', '{request.body#/callbackReference}','post'): {'interface':'N8','dir':'1','msgType':'50048','response':{'204':'Successful Notification response','307':'Temporary Redirect','308':'Permanent Redirect','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sdm-subscriptions/{subscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50050','response':{'204':'Successful response','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/sdm-subscriptions/{subscriptionId}', 'patch')] = {'interface':'N8','dir':'0','msgType':'50052','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{ueId}/id-translation-result', 'get')] = {'interface':'N8','dir':'0','msgType':'50054','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/am-data/sor-ack', 'put')] = {'interface':'N8','dir':'0','msgType':'50056','response':{'204':'Successful acknowledgement','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/am-data/upu-ack', 'put')] = {'interface':'N8','dir':'0','msgType':'50058','response':{'204':'Successful acknowledgement','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/am-data/subscribed-snssais-ack', 'put')] = {'interface':'N8','dir':'0','msgType':'50060','response':{'204':'Successful acknowledgement','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/{supi}/am-data/cag-ack', 'put')] = {'interface':'N8','dir':'0','msgType':'50062','response':{'204':'Successful acknowledgement','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/shared-data', 'get')] = {'interface':'N8','dir':'0','msgType':'50064','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/shared-data-subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50066','response':{'201':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{('datachangeNotification', '{request.body#/callbackReference}','post'): {'interface':'N8','dir':'1','msgType':'50068','response':{'204':'Successful Notification response','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/shared-data-subscriptions/{subscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50070','response':{'204':'Successful response','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/shared-data-subscriptions/{subscriptionId}', 'patch')] = {'interface':'N8','dir':'0','msgType':'50072','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-sdm/v2', '/group-data/group-identifiers', 'get')] = {'interface':'N8','dir':'0','msgType':'50074','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}

# TS29503_Nudm_UECM.yaml
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-3gpp-access', 'put')] = {'interface':'N8','dir':'0','msgType':'50078','response':{'201':'Created','200':'OK','204':'No content','default':'Unexpected error',},'callbacks':{('deregistrationeNotification', '{request.body#/deregCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50080','response':{'204':'Successful Notification response','default':'Unexpected error',}},('pcscfRestorationNotification', '{request.body#/pcscfRestorationCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50082','response':{'204':'Successful Notification response','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-3gpp-access', 'patch')] = {'interface':'N8','dir':'0','msgType':'50084','response':{'200':'Expected response to a valid request','204':'Expected response to a valid request','422':'Unprocessable Request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-3gpp-access', 'get')] = {'interface':'N8','dir':'0','msgType':'50086','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-non-3gpp-access', 'put')] = {'interface':'N8','dir':'0','msgType':'50088','response':{'201':'Created','200':'OK','204':'No Content','default':'Unexpected error',},'callbacks':{('deregistrationeNotification', '{request.body#/deregCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50090','response':{'204':'Successful Notification response','default':'Unexpected error',}},('pcscfRestorationNotification', '{request.body#/pcscfRestorationCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50092','response':{'204':'Successful Notification response','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-non-3gpp-access', 'patch')] = {'interface':'N8','dir':'0','msgType':'50094','response':{'200':'Expected response to a valid request','204':'Expected response to a valid request','422':'Unprocessable Request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/amf-non-3gpp-access', 'get')] = {'interface':'N8','dir':'0','msgType':'50096','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smf-registrations/{pduSessionId}', 'put')] = {'interface':'N10','dir':'1','msgType':'50098','response':{'201':'Created','200':'Expected response to a valid request','204':'No content','default':'Unexpected error',},'callbacks':{('pcscfRestorationNotification', '{request.body#/pcscfRestorationCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50100','response':{'204':'Successful Notification response','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smf-registrations/{pduSessionId}', 'delete')] = {'interface':'N10','dir':'1','msgType':'50102','response':{'204':'Expected response to a valid request','422':'Unprocessable Request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-3gpp-access', 'put')] = {'interface':'N21','dir':'1','msgType':'50104','response':{'201':'Created','200':'Expected response to a valid request','204':'No content','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-3gpp-access', 'delete')] = {'interface':'N21','dir':'1','msgType':'50106','response':{'204':'Expected response to a valid request','422':'Unprocessable Request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-3gpp-access', 'get')] = {'interface':'N21','dir':'1','msgType':'50108','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-non-3gpp-access', 'put')] = {'interface':'N21','dir':'1','msgType':'50110','response':{'201':'Created','200':'Expected response to a valid request','204':'No content','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-non-3gpp-access', 'delete')] = {'interface':'N21','dir':'1','msgType':'50112','response':{'204':'Expected response to a valid request','422':'Unprocessable Request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/{ueId}/registrations/smsf-non-3gpp-access', 'get')] = {'interface':'N21','dir':'1','msgType':'50114','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nudm-uecm/v1', '/restore-pcscf', 'post')] = {'interface':'N8','dir':'0','msgType':'50116','response':{'204':'Successful response','default':'Unexpected error',},'callbacks':{}}

# TS29507_Npcf_AMPolicyControl.yaml
sbi_dict[('{apiRoot}/npcf-am-policy-control/v1', '/policies', 'post')] = {'interface':'N15','dir':'0','msgType':'50120','response':{'201':'Created',},'callbacks':{('policyUpdateNotification', '{$request.body#/notificationUri}/update','post'): {'interface':'N15','dir':'1','msgType':'50122','response':{'204':'No Content, Notification was succesfull','307':'temporary redirect',}},('policyAssocitionTerminationRequestNotification', '{$request.body#/notificationUri}/terminate','post'): {'interface':'N15','dir':'1','msgType':'50124','response':{'204':'No Content, Notification was succesfull','307':'temporary redirect',}},}}
sbi_dict[('{apiRoot}/npcf-am-policy-control/v1', '/policies/{polAssoId}', 'get')] = {'interface':'N15','dir':'0','msgType':'50126','response':{'200':'OK. Resource representation is returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-am-policy-control/v1', '/policies/{polAssoId}', 'delete')] = {'interface':'N15','dir':'0','msgType':'50128','response':{'204':'No Content. Resource was succesfully deleted',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-am-policy-control/v1', '/policies/{polAssoId}/update', 'post')] = {'interface':'N15','dir':'0','msgType':'50130','response':{'200':'OK. Updated policies are returned',},'callbacks':{}}

# TS29508_Nsmf_EventExposure.yaml
sbi_dict[('{apiRoot}/nsmf_event-exposure/v1', '/subscriptions', 'post')] = {'interface':'N11','dir':'0','msgType':'50134','response':{'201':'Success',},'callbacks':{('myNotification', '{$request.body#/notifUri}','post'): {'interface':'N11','dir':'1','msgType':'50136','response':{'204':'No Content, Notification was succesfull','307':'temporary redirect',}},}}
sbi_dict[('{apiRoot}/nsmf_event-exposure/v1', '/subscriptions/{subId}', 'get')] = {'interface':'N11','dir':'0','msgType':'50138','response':{'200':'OK. Resource representation is returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf_event-exposure/v1', '/subscriptions/{subId}', 'put')] = {'interface':'N11','dir':'0','msgType':'50140','response':{'200':'OK. Resource was succesfully modified and representation is returned','204':'No Content. Resource was succesfully modified',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmf_event-exposure/v1', '/subscriptions/{subId}', 'delete')] = {'interface':'N11','dir':'0','msgType':'50142','response':{'204':'No Content. Resource was succesfully deleted',},'callbacks':{}}

# TS29509_Nausf_UEAuthentication.yaml
sbi_dict[('{apiRoot}/nausf-auth/v1', '/ue-authentications', 'post')] = {'interface':'N12','dir':'0','msgType':'50146','response':{'201':'UEAuthenticationCtx','400':'Bad Request from the AMF','403':'Forbidden due to serving network not authorized','404':'User does not exist in the HPLMN','500':'Internal Server Error','501':'Received protection scheme is not supported by HPLMN',},'callbacks':{}}
sbi_dict[('{apiRoot}/nausf-auth/v1', '/ue-authentications/{authCtxId}/5g-aka-confirmation', 'put')] = {'interface':'N12','dir':'0','msgType':'50148','response':{'200':'Request processed (EAP success or Failure)','400':'Bad Request','500':'Internal Server Error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nausf-auth/v1', '/ue-authentications/{authCtxId}/eap-session', 'post')] = {'interface':'N12','dir':'0','msgType':'50150','response':{'200':'Use to handle or close the EAP session','400':'Bad Request','500':'Internal Server Error',},'callbacks':{}}

# TS29510_Nnrf_AccessToken.yaml

# TS29510_Nnrf_NFDiscovery.yaml
sbi_dict[('{apiRoot}/nnrf-disc/v1', '/nf-instances', 'get')] = {'interface':'Nrf','dir':'0','msgType':'50156','response':{'200':'Expected response to a valid request','307':'Temporary Redirect',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-disc/v1', '/searches/{searchId}', 'get')] = {'interface':'Nrf','dir':'0','msgType':'50158','response':{},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-disc/v1', '/searches/{searchId}/complete', 'get')] = {'interface':'Nrf','dir':'0','msgType':'50160','response':{},'callbacks':{}}

# TS29510_Nnrf_NFManagement.yaml
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances', 'get')] = {'interface':'Nrf','dir':'0','msgType':'50164','response':{'200':'Expected response to a valid request',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances', 'options')] = {'interface':'Nrf','dir':'0','msgType':'50166','response':{'200':'OK',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances/{nfInstanceID}', 'get')] = {'interface':'Nrf','dir':'0','msgType':'50168','response':{'200':'Expected response to a valid request',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances/{nfInstanceID}', 'put')] = {'interface':'Nrf','dir':'0','msgType':'50170','response':{'200':'OK (Profile Replacement)','201':'Expected response to a valid request',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances/{nfInstanceID}', 'patch')] = {'interface':'Nrf','dir':'0','msgType':'50172','response':{'200':'Expected response to a valid request','204':'Expected response with empty body',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/nf-instances/{nfInstanceID}', 'delete')] = {'interface':'Nrf','dir':'0','msgType':'50174','response':{'204':'Expected response to a successful deregistration',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/subscriptions', 'post')] = {'interface':'Nrf','dir':'0','msgType':'50176','response':{'201':'Expected response to a valid request',},'callbacks':{('onNFStatusEvent', '{$request.body#/nfStatusNotificationUri}','post'): {'interface':'NRF','dir':'1','msgType':'50178','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/subscriptions/{subscriptionID}', 'patch')] = {'interface':'Nrf','dir':'0','msgType':'50180','response':{'200':'Expected response to a valid request','204':'No Content',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnrf-nfm/v1', '/subscriptions/{subscriptionID}', 'delete')] = {'interface':'Nrf','dir':'0','msgType':'50182','response':{'204':'Expected response to a successful subscription removal',},'callbacks':{}}

# TS29512_Npcf_SMPolicyControl.yaml
sbi_dict[('{apiRoot}/npcf-smpolicycontrol/v1', '/sm-policies', 'post')] = {'interface':'N7','dir':'0','msgType':'50186','response':{'201':'Created','404':'Not Found',},'callbacks':{('SmPolicyUpdateNotification', '{$request.body#/notificationUri}/update','post'): {'interface':'N7','dir':'1','msgType':'50188','response':{'200':'OK. The current applicable values corresponding to the policy control request trigger is reported','204':'No Content, Notification was succesfull','400':'Bad Request.',}},('SmPolicyControlTerminationRequestNotification', '{$request.body#/notificationUri}/terminate','post'): {'interface':'N7','dir':'1','msgType':'50190','response':{'204':'No Content, Notification was succesful',}},}}
sbi_dict[('{apiRoot}/npcf-smpolicycontrol/v1', '/sm-policies/{smPolicyId}', 'get')] = {'interface':'N7','dir':'0','msgType':'50192','response':{'200':'OK. Resource representation is returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-smpolicycontrol/v1', '/sm-policies/{smPolicyId}/update', 'post')] = {'interface':'N7','dir':'0','msgType':'50194','response':{'200':'OK. Updated policies are returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-smpolicycontrol/v1', '/sm-policies/{smPolicyId}/delete', 'post')] = {'interface':'N7','dir':'0','msgType':'50196','response':{'204':'No content',},'callbacks':{}}

# TS29514_Npcf_PolicyAuthorization.yaml
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions', 'post')] = {'interface':'N5','dir':'1','msgType':'50200','response':{'201':'Successful creation of the resource','303':'See Other. The result of the HTTP POST request would be equivalent to the existing Application Session Context. The HTTP response shall contain a Location header field set to the URI of the existing individual Application Session Context resource','403':'Forbidden',},'callbacks':{('terminationRequest', '{$request.body#/ascReqData/notifUri}/terminate','post'): {'interface':'N5','dir':'1','msgType':'50202','response':{'204':'The receipt of the notification is acknowledged.',}},('eventNotification', '{$request.body#/ascReqData/evSubsc/notifUri}/notify','post'): {'interface':'N5','dir':'1','msgType':'50204','response':{'204':'The receipt of the notification is acknowledged',}},}}
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions/{appSessionId}', 'get')] = {'interface':'N5','dir':'1','msgType':'50206','response':{'200':'A representation of the resource is returned.',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions/{appSessionId}', 'patch')] = {'interface':'N5','dir':'1','msgType':'50208','response':{'200':'successful modification of the resource and a representation of that resource is returned','204':'The successful modification','403':'Forbidden',},'callbacks':{('eventNotification', '{$request.body#/evSubsc/notifUri}/notify','post'): {'interface':'N5','dir':'1','msgType':'50210','response':{'204':'The receipt of the notification is acknowledged',}},}}
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions/{appSessionId}/delete', 'post')] = {'interface':'N5','dir':'1','msgType':'50212','response':{'200':'The deletion of the resource is confirmed and a resource is returned','204':'The deletion is confirmed without returning additional data.',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions/{appSessionId}/events-subscription', 'put')] = {'interface':'N5','dir':'1','msgType':'50214','response':{'201':'The creation of the Events Subscription resource is confirmed and its representation is returned.','200':'The modification of the of the Events Subscription resource is confirmed its representation is returned.','204':'The modification of the Events Subscription subresource is confirmed without returning additional data.',},'callbacks':{('eventNotification', '{$request.body#/notifUri}/notify','post'): {'interface':'N5','dir':'1','msgType':'50216','response':{'204':'The receipt of the notification is acknowledged.',}},}}
sbi_dict[('{apiRoot}/npcf-policyauthorization/v1', '/app-sessions/{appSessionId}/events-subscription', 'delete')] = {'interface':'N5','dir':'1','msgType':'50218','response':{'204':'The deletion of the of the Events Subscription sub-resource is confirmed without returning additional data.',},'callbacks':{}}

# TS29518_Namf_Communication.yaml
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}', 'put')] = {'interface':'N14','dir':'0','msgType':'50222','response':{'201':'UE context successfully created.','400':'Bad Request','403':'Forbidden','500':'Internal Server Error','default':'Unexpected error',},'callbacks':{('onN2MessageNotify', '{$request.body#/n2NotifyUri}','post'): {'interface':'N8','dir':'1','msgType':'50224','response':{'200':'N2 Information Notification Response.','204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/release', 'post')] = {'interface':'N14','dir':'0','msgType':'50226','response':{'204':'UE Context successfully released','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/assign-ebi', 'post')] = {'interface':'N11','dir':'1','msgType':'50228','response':{'200':'EBI Assignment successfully performed.','400':'Bad Request','403':'Forbidden','500':'Internal Server Error','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/transfer', 'post')] = {'interface':'N14','dir':'0','msgType':'50230','response':{'200':'UE context transfer successfully initiated.','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/transfer-update', 'post')] = {'interface':'N14','dir':'0','msgType':'50232','response':{'200':'UE context transfer status successfully updated.',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/n1-n2-messages', 'post')] = {'interface':'N11','dir':'1','msgType':'50234','response':{'202':'N1N2 Message Transfer accepted.','200':'N1N2 Message Transfer successfully initiated.','307':'Temporary Redirect','409':'Conflicts','504':'Gateway Timeout','default':'Unexpected error',},'callbacks':{('onN1N2TransferFailure', '{$request.body#/n1n2FailureTxfNotifURI}','post'): {'interface':'N11','dir':'0','msgType':'50236','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/n1-n2-messages/subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50238','response':{'201':'N1N2 Message Subscription successfully created.','default':'Unexpected error',},'callbacks':{('onN1N2MessageNotify', '{$request.body#/n1NotifyCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50240','response':{'204':'Expected response to a successful callback processing',}},('onN1N2MessageNotify', '{$request.body#/n2NotifyCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50242','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/ue-contexts/{ueContextId}/n1-n2-messages/subscriptions/{subscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50244','response':{'204':'N1N2 Message Subscription successfully removed.',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/non-ue-n2-messages/transfer', 'post')] = {'interface':'N8','dir':'0','msgType':'50246','response':{'200':'Non UE N2 Message Transfer successfully initiated.','400':'Bad Request','403':'Forbidden','404':'Not Found','500':'Internal Server Error','503':'Service Unavailable','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/non-ue-n2-messages/subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50248','response':{'201':'Non UE N2 Info Subscription successfully created.','default':'Unexpected error',},'callbacks':{('onN2InfoNotify', '{$request.body#/n2NotifyCallbackUri}','post'): {'interface':'N8','dir':'1','msgType':'50250','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/non-ue-n2-messages/subscriptions/{n2NotifySubscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50252','response':{'204':'Non UE N2 INfo Subscription successfully removed.',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50254','response':{'201':'N1N2 Message Subscription successfully created.','default':'Unexpected error',},'callbacks':{('onAmfStatusChange', '{$request.body#/amfStatusUri}','post'): {'interface':'N8','dir':'1','msgType':'50256','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/subscriptions/{subscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50258','response':{'204':'N1N2 Message Subscription successfully removed.','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-comm/v1', '/subscriptions/{subscriptionId}', 'put')] = {'interface':'N8','dir':'0','msgType':'50260','response':{'202':'N1N2 Message Subscription successfully updated.','default':'Unexpected error',},'callbacks':{('OnAmfStatusChange', '{$request.body#/amfStatusUri}','post'): {'interface':'N8','dir':'1','msgType':'50262','response':{'204':'Expected response to a successful callback processing',}},}}

# TS29518_Namf_EventExposure.yaml
sbi_dict[('{apiRoot}/namf-evts/v1', '/subscriptions', 'post')] = {'interface':'N8','dir':'0','msgType':'50266','response':{'201':'Subsription Created','default':'Unexpected error',},'callbacks':{('onEventReport', '{$request.body#/subscription/eventNotifyUri}','post'): {'interface':'N8','dir':'1','msgType':'50268','response':{'204':'Successful acknowledgement','default':'Unexpected error',}},('onSubscriptionIdChangeEvtReport', '{$request.body#/subscription/subsChangeNotifyUri}','post'): {'interface':'N8','dir':'1','msgType':'50270','response':{'204':'Successful acknowledgement','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/namf-evts/v1', '/subscriptions/{subscriptionId}', 'patch')] = {'interface':'N8','dir':'0','msgType':'50272','response':{'200':'Subsription modified successfully','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-evts/v1', '/subscriptions/{subscriptionId}', 'delete')] = {'interface':'N8','dir':'0','msgType':'50274','response':{'204':'Subsription deleted successfully','default':'Unexpected error',},'callbacks':{}}

# TS29518_Namf_Location.yaml
sbi_dict[('{apiRoot}/namf-loc/v1', '/{ueContextId}/provide-pos-info', 'post')] = {'interface':'N8','dir':'0','msgType':'50278','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{('onUELocationNotification', '{$request.body#/locationNotificationUri}','post'): {'interface':'N8','dir':'1','msgType':'50280','response':{'204':'Expected response to a successful callback processing',}},}}
sbi_dict[('{apiRoot}/namf-loc/v1', '/{ueContextId}/provide-loc-info', 'post')] = {'interface':'N8','dir':'0','msgType':'50282','response':{'200':'Expected response to a valid request','default':'Unexpected error',},'callbacks':{}}

# TS29518_Namf_MT.yaml
sbi_dict[('{apiRoot}/namf-mt/v1', '/ue-contexts/{ueContextId}', 'get')] = {'interface':'N8','dir':'0','msgType':'50286','response':{'200':'Requested UE Context Information returned','307':'Temporary Redirect','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/namf-mt/v1', '/ue-contexts/{ueContextId}/ue-reachind', 'put')] = {'interface':'N8','dir':'0','msgType':'50288','response':{'200':'UE has become reachable as desired','307':'Temporary Redirect','403':'Forbidden','504':'Gateway Timeout','default':'Unexpected error',},'callbacks':{}}

# TS29525_Npcf_UEPolicyControl.yaml
sbi_dict[('{apiRoot}/npcf-ue-policy-control/v1', '/policies', 'post')] = {'interface':'N15','dir':'0','msgType':'50292','response':{'201':'Created',},'callbacks':{('policyUpdateNotification', '{$request.body#/notificationUri}/update','post'): {'interface':'N15','dir':'1','msgType':'50294','response':{'204':'No Content, Notification was succesfull',}},('policyAssocitionTerminationRequestNotification', '{$request.body#/notificationUri}/terminate','post'): {'interface':'N15','dir':'1','msgType':'50296','response':{'204':'No Content, Notification was succesfull','307':'temporary redirect',}},}}
sbi_dict[('{apiRoot}/npcf-ue-policy-control/v1', '/policies/{polAssoId}', 'get')] = {'interface':'N15','dir':'0','msgType':'50298','response':{'200':'OK. Resource representation is returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-ue-policy-control/v1', '/policies/{polAssoId}', 'delete')] = {'interface':'N15','dir':'0','msgType':'50300','response':{'204':'No Content. Resource was succesfully deleted',},'callbacks':{}}
sbi_dict[('{apiRoot}/npcf-ue-policy-control/v1', '/policies/{polAssoId}/update', 'post')] = {'interface':'N15','dir':'0','msgType':'50302','response':{'200':'OK. Updated policies are returned',},'callbacks':{}}

# TS29531_Nnssf_NSSAIAvailability.yaml
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability/{nfId}', 'put')] = {'interface':'N22','dir':'0','msgType':'50306','response':{'200':'OK (Successful update of SNSSAI information per TA)','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability/{nfId}', 'patch')] = {'interface':'N22','dir':'0','msgType':'50308','response':{'200':'OK (Successful update of SNSSAI information per TA)','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability/{nfId}', 'delete')] = {'interface':'N22','dir':'0','msgType':'50310','response':{'204':'No Content (Successful deletion of SNSSAI information per TA)','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability/subscriptions', 'post')] = {'interface':'N22','dir':'0','msgType':'50312','response':{'201':'Created (Successful creation of subscription for notification)','default':'Unexpected error',},'callbacks':{('nssaiAvailabilityNotification', '{request.body#/nfNssaiAvailabilityUri}','post'): {'interface':'N22','dir':'1','msgType':'50314','response':{'204':'No Content (successful notification)','default':'Unexpected error',}},}}
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability/subscriptions/{subscriptionId}', 'delete')] = {'interface':'N22','dir':'0','msgType':'50316','response':{'204':'No Content (Successful deletion of subscription for NSSAI Availability notification)','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nnssf-nssaiavailability/v1', '/nssai-availability', 'options')] = {'interface':'N22','dir':'0','msgType':'50318','response':{'200':'OK',},'callbacks':{}}

# TS29531_Nnssf_NSSelection.yaml
sbi_dict[('{apiRoot}/nnssf-nsselection/v2', '/network-slice-information', 'get')] = {'interface':'N22','dir':'0','msgType':'50322','response':{'200':'OK (Successful Network Slice Selection)','default':'Unexpected error',},'callbacks':{}}

# TS29540_Nsmsf_SMService.yaml
sbi_dict[('{apiRoot}/nsmsf-sms/v2', '/ue-contexts/{supi}', 'put')] = {'interface':'N20','dir':'0','msgType':'50326','response':{'201':'UE Context for SMS is created in SMSF','204':'UE Context for SMS is updated in SMSF','400':'Invalid Service Request','403':'Unable to create/update UE Context for SMS in SMSF','404':'Unable to found subscription for service user or UE Context for SMS in SMSF','503':'Service Unavailable','default':'Unexpected error',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmsf-sms/v2', '/ue-contexts/{supi}', 'delete')] = {'interface':'N20','dir':'0','msgType':'50328','response':{'204':'UE Context for SMS is deleted from SMSF','400':'Invalid Service Request','404':'Unable to found UE Context for SMS in SMSF','503':'Service Unavailable',},'callbacks':{}}
sbi_dict[('{apiRoot}/nsmsf-sms/v2', '/ue-contexts/{supi}/sendsms', 'post')] = {'interface':'N20','dir':'0','msgType':'50330','response':{'200':'SMS payload is received by SMSF, and is being delivered out','400':'Invalid Service Request','403':'Unable to deliver SMS at SMSF','404':'Unable to found UE Context for SMS in SMSF','503':'Service Unavailable',},'callbacks':{}}

# TS29594_Nchf_SpendingLimitControl.yaml
sbi_dict[('{apiRoot}/nchf-spendinglimitcontrol/v1', '/subscriptions', 'post')] = {'interface':'N40','dir':'0','msgType':'50334','response':{'201':'Success',},'callbacks':{('statusNotification', '{$request.body#/notifUri}/notify','post'): {'interface':'N40','dir':'1','msgType':'50336','response':{'204':'No Content, Notification was succesfull',}},('subscriptionTermination', '{$request.body#/notifUri}/terminate','post'): {'interface':'N40','dir':'1','msgType':'50338','response':{'204':'No Content, Notification was succesfull',}},}}
sbi_dict[('{apiRoot}/nchf-spendinglimitcontrol/v1', '/subscriptions/{subscriptionId}', 'put')] = {'interface':'N40','dir':'0','msgType':'50340','response':{'200':'OK. Resource was succesfully modified and representation is returned',},'callbacks':{}}
sbi_dict[('{apiRoot}/nchf-spendinglimitcontrol/v1', '/subscriptions/{subscriptionId}', 'delete')] = {'interface':'N40','dir':'0','msgType':'50342','response':{'204':'No Content. Resource was succesfully deleted',},'callbacks':{}}

# TS29521_Nbsf_Management.yaml
sbi_dict[('{apiRoot}/nbsf-management/v1', '/pcfBindings', 'post')] = {'interface':'Nbsf','dir':'0','msgType':'50346','response':{'201':'The creation of an individual PCF session binding.',},'callbacks':{}}
sbi_dict[('{apiRoot}/nbsf-management/v1', '/pcfBindings', 'get')] = {'interface':'Nbsf','dir':'0','msgType':'50348','response':{'200':'The individual PCF session binding session binding information resource matching the query parameter(s) is returned.','204':'There is no PCF session binding information matching the query parameter(s).',},'callbacks':{}}
sbi_dict[('{apiRoot}/nbsf-management/v1', '/pcfBindings/{bindingId}', 'delete')] = {'interface':'Nbsf','dir':'0','msgType':'50350','response':{'204':'No Content. The Individual PCF session binding information resource is deleted.',},'callbacks':{}}
sbi_dict[('{apiRoot}/nbsf-management/v1', '/pcfBindings/{bindingId}', 'patch')] = {'interface':'Nbsf','dir':'0','msgType':'50352','response':{'200':'OK (Successful update of the session binding)',},'callbacks':{}}
