[Generic]
	# 1: cp master mode; 2: cp slave mode; 3: up mode; 0/4: cp/up mode;
	DecoderMode = 0
	
	# dispatch thread number. default is processed by decoder. Range:[0-5]
	DispatchNum = 0
	
	# CP dispatch thread number. default is processed by decoder. Range:[0-5]
	DispatchNum_CP = 1
	
	#S1-MME thread number. default is processed by decoder. Range:[0-32]
	S1CThreadNum = 0
	
	#S11 thread number. default is processed by decoder. Range:[0-32]
	S11ThreadNum = 0
	
	#Mc thread number. default is processed by decoder. Range:[0-32]
	MCThreadNum = 0
	
	#Delay cache msgs. valid when memory more than 64G byte. Range:[1024000-10240000]
	Delay_Cache_Msgs = 1024000

    #Sgs and GnGp thread core Switch: On or Off, default is Off
	#On means GnGp and Sgs threads have a single core, Off means share a core with scp
	Sgs_GnGp_Single_Core = Off

    #S1 Decoding Switch: On or Off, default is On
	#On means S1 features are enabled, Off means both are disabled
    S1_Decoding_Switch = On

	#S10 Decoding Switch:  On or Off, default is On
	#On means S10 feature is enabled, Off means disabled
    S10_Decoding_Switch = On
	
    #S11 Decoding Switch:  On or Off, default is On
	#On means S11 feature is enabled, Off means disabled
    S11_Decoding_Switch = On

	#S5S8 Decoding Switch: On or Off, default is On
	#On means S5S8 features are enabled, Off means both are disabled
    S5S8_Decoding_Switch = On

    #S6a Decoding Switch:  On or Off, default is On
	#On means S6a feature is enabled, Off means disabled
    S6a_Decoding_Switch = On

    #Sgs Decoding Switch:  On or Off, default is On
	#On means Sgs feature is enabled, Off means disabled
    Sgs_Decoding_Switch = On

    #GnGp Decoding Switch:  On or Off, default is On
	#On means Sgs feature is enabled, Off means disabled
    GnGp_Decoding_Switch = On

    #STa Decoding Switch:  On or Off, default is On
	#On means STa feature is enabled, Off means disabled
    STa_Decoding_Switch = On

	#S2a Decoding Switch: On or Off, default is On
	#On means S2a feature is enabled, Off means disabled
    S2a_Decoding_Switch = On

	#Gx Decoding Switch: On or Off, default is On
	#On means Gx feature is enabled, Off means disabled
    Gx_Decoding_Switch = On

	#Gy Decoding Switch: On or Off, default is On
	#On means Gy feature is enabled, Off means disabled
    Gy_Decoding_Switch = On
	
	#Mc Decoding Switch:  On or Off, default is On
	#On means Mc feature is enabled, Off means disabled
    Mc_Decoding_Switch = Off

	#Mc with lte Imsi Filter Switch:  On or Off, default is On
	#On means feature is enabled, Off means disabled
    Mc_ImsiFilter_Switch = On

	#Mc Only decoding CSFB Msg Switch: On or Off, default is Off
	#On means feature is enabled, Off means disabled	
	Mc_Decoding_Only_CSFB = Off

	#NAS Decrypt Switch: On or Off or Auto, default is Auto
	#On means nas layer decrypt is enabled, Off means disabled, auto means learning
	Nas_Decrypt_Switch = Auto

	#S1U Dispatch Links Switch: On or Off, default is On
	#On means s1u packet dispatch by tcp links, Off means s1u packet dispatch by imsi
	S1U_Dispatch_Links = Off

	# S6a Duplicate Msg Filter Switch: On or Off, default is Off
	# On means S6a feature is enabled, Off means disabled
	S6a_DupMsgFilter_Switch = Off
	
	# S11 Duplicate Msg Filter Switch: On or Off, default is Off
	# On means S11 feature is enabled, Off means disabled
	S11_DupMsgFilter_Switch = Off
	
	# S5S8 Duplicate Msg Filter Switch: On or Off, default is Off
	# On means S5S8 feature is enabled, Off means disabled
	S5S8_DupMsgFilter_Switch = Off
	
	# S10 Duplicate Msg Filter Switch: On or Off, default is Off
	# On means S10 feature is enabled, Off means disabled
	S10_DupMsgFilter_Switch = On
	
	#Support BREC SDK lib enable, TRUE or FALSE
	LibBRECEnable = TRUE

	#Support numberic binary rules enable, TRUE or FALSE
	NumericBinary = FALSE

	#Support numberic ftp rules enable, TRUE or FALSE
	NumericFtp    = FALSE

	#Converge session enable, TRUE or FALSE
	ConvergeEnable = TRUE

	#Converge timeout timer(s), default is 60s
	ConvergeTimer = 60

	#Learning timer(s), default is 60s
	LearningTimer = 15

	#Dns Learning timer(minutes), default is 60minutes=1hour
	DnsLearningTime = 60
	
	#duplicate Msg check mode: AUTO or TRUE or FALSE, by default: AUTO
	DupMsgCheck = AUTO

	#Mids function enable, TRUE or FALSE 
	MidsEnable = FALSE

	#WapGateWay, CMCC:10.0.0.172, CUCC: :10.0.0.172, CTCC:10.0.0.200
	Wap_GateWay = 10.0.0.172

	#The Number of 'N' for Outputing the First 'N' Downlink Payload Packet's TimeStamp, default is 100
	TS_PL_PKT_DL_N = 100
	
	#Decoder instance id
	InstanceId = 1

	#Decoder restart times
	RestartId = 0

	#Heartbeat interval timer
	HeartbeatInterval = 200

	# Log file max size, in Byte
	LogFileMaxSize = 67108865

	# In case no USB check.
	DefaultFlowRateLimitation=1000

	# The second output path 
	OutputPath = 

[ImeiLearning]
	ImeiFilePath=./

	# in seconds. hourly by default
	ImeiPersistenceDuration=3600

	# Bufferred imei updates before flushed into imeiTable file
	ImeiWriteBufferSize=50000

[TCPIP]
	MTU = 1500

[Service]
	# S6aPortList(SCTP), example: 3868,3869,3870,2001-2004,4001,4002,5001,5002
	S6aPortList = 3868
	
	# S6aAddrList(SCTP), example: 115.169.139.102, 115.169.139.105
	S6aAddrList = 
	
	# GxPortList(TCP), example: 3868,3869,3870,2001-2004,4001,4002,5001,5002
	GxPortList = 
	
	# GxAddrList(TCP), example: 10.16.0.120, 10.16.0.247
	GxAddrList = 
	
	# GyPortList(TCP), example: 8001,8002
	GyPortList = 
	
	# GyAddrList(TCP), example: 134.192.249.81, 134.192.249.82
	GyAddrList = 
	
	# S6aPortList(SCTP), example: 29118,29119,29118-29119
	SGsPortList = 29118,29119
	
	# SGsAddrList(SCTP), example: 10.16.0.120, 10.16.0.247
	SGsAddrList = 
	
	# 4 ports in max, defaule is 9201, 9203
	ConnectionWapPortList = 9201, 9203
	
	# 4 ports in max, defaule is 9202, 9200
	ConnectlessWapPortList = 9202, 9200

	# UP SuccFlag Protocol Error: UE.Error or SP.Error
	HTTP.UE.ERR   = 401,405,411,422,403,505,400,416,424,426,449,408
	HTTP.SP.ERR   = 404,406,410,412,423,409,421,503,507,509,500,502,504,413,415,501,417,506,510
	WAP.UE.ERR 	  = 1,2,3,4,5,6,10,224,230,231,232,234,235,238,414
	WAP.GW.ERR 	  = 0,7,8,9,225,228,229,233,236,237
	FTP.UE.ERR 	  = 421,425,426,501,502,503,504,530,532,550,553
	FTP.SP.ERR 	  = 450,451,452,551,552
	DNS.UE.ERR    = 1,3
	DNS.SP.ERR    = 2,4,5,6,7,8,9,10,16,16,17,18,19,20,21,22
	MMS.MO.UE.ERR = 130,131,136,225,226,234
	MMS.MO.GW.ERR = 129,132,133,134,135,192,193,194,195,224,227,228,229
	MMS.MT.UE.ERR = 130,131,132,133,134,225,227
	MMS.MT.GW.ERR = 135,192,193,194,224,226
	SMTP.UE.ERR   = 500,501,503,550,551,553
	SMTP.SP.ERR   = 421,450,451,452,455,502,504,552,554,555

	#Dss TopicVideo Switch: On or Off, default is Off
	DSS_TopicVideo_Switch = On
	
	#Dss WeiXin Action Switch: On or Off, default is On
	DSS_WeiXinAction_Switch = On
	
[Analysis]
	#In kbps, to define the range of slice values
	SliceSpeeds=0,60,500,4096

	#In seconds, Min=0, Default=120, Max=600
	PostponeImsiAssociationTimer = 60
	
	#In millisecond, Min=10, Max=60000, = 240x250 = 500x120
	#Reference: T3192/T3193 Values (500, 1000, 1500, 0, 80, 120, 160, 200) ms
	CellStatsScale  = 300
	OnlineTimeScale =  80

	# Below two parameters are INTERNAL USE ONLY, default=10000,150000
	DefaultRuntimeCellNum =10000
	DefaultRuntimeMsNum =10000

	MsidMultipleFactor = 0
	DssMultipleFactor = 3

	#In sec, Min=60, Max=3600
	ImsiAliveTimer = 360
	
[Export]
	#In MBytes, Min=1, Default=10, Max=1024
	# Ascii=10M, Binary=5M
	FileSlicingSize = 5
	
	DisableOutput = 0
	#In minutes, Min=1, Default = 10, Max = 60
	FileSlicingInterval = 1
	
	#export format, Binary or Ascii
	Format = Ascii

	ImsiEncryMode = 0
	
	#CGI_ENBID_MSISDN Switch: On or Off, default is On
	CGI_ENBID_MSISDN_Switch = On
	
	PrintIpTraffic = 0
	
	#Print control pane message raw data enable, 1 or 0	
	PrintRawBin = 1
	
	#Whether export the TCP Sync/Ack/Fin tables, 0 or 1
	PrintTcpShakehand = 0
	
[ImsiFilter]
	# 0:None, 1:save, 2:send, 3:save and send
	FilterMode = 0

	# send filter packet ip address
	IpAddress =   

	# send filter net adapter name, for example NIC4
	NetAdapter = NIC4
		
	# save filter files path
	OutputPath =E:\Dolphin_Platform\filter\ 

	# File sliceing size in MByte, Min=5MB, Default=32MB, Max=128MB
	FileSlicingSize = 32

[E10Sender]
	# E10 Sender Port IP Address and L2 layer sip address
	E10_Sender_Sip = 127.0.0.1
	
	# E10 Sender L2 layer dip for broadcast
	E10_Sender_Dip = 127.0.0.1
	
	# E10 Sender ENB_CGI Notify Msg Switch:  On or Off, default is On
	E10_Sender_ENB_CGI_Switch =Off
	
	# E10 Sender Imsi_CGI Notify Msg Switch:  On or Off, default is Off
	E10_Sender_Imsi_CGI_Switch = Off
	
[Timer]
	ToleranceRate = 1.1
	
	# ProcedureName  = timer(ms), max_retrans
	HANDOVER_PREPARATION						= 1000, 1  
	HANDOVER_RESOURCE_ALLOCATION				= 1000, 1  
	PATH_SWITCH_REQUEST							= 1000, 1  
	HANDOVER_CANCELLATION						= 1000, 1  
	E_RAB_SETUP									= 1000, 1  
	E_RAB_MODIFY								= 1000, 1  
	E_RAB_RELEASE								= 1000, 1  
	INITIAL_CONTEXT_SETUP						= 1000, 1  
	RESET										= 1000, 1  
	S1_SETUP									= 1000, 1  
	UE_CONTEXT_RELEASE							= 1000, 1  
	UE_CONTEXT_MODIFICATION						= 1000, 1  
	ENB_CONFIGURATION_UPDATE					= 1000, 1  
	MME_CONFIGURATION_UPDATE					= 1000, 1  
	WRITE_REPLACE_WARNING						= 1000, 1  
	KILL										= 1000, 1  

	ATTACH  									= 15000, 5  
	ATTACH_ACCEPT								= 6000,  5  
	AUTHENTICATION   							= 6000,  5  
	DETACH_UE_ORIGINATING  						= 15000, 5  
	DETACH_UE_TERMINATED						= 6000,  5  
	GUTI_REALLOCATION  							= 6000,  5  
	IDENTIFICATION  							= 6000,  5  
	SECURITY_MODE_CONTROL						= 6000,  5  
	SERVICE_REQUEST 							= 5000,  1 
	EXT_SERVICE_REQUEST 						= 10000, 1 
	TRACKING_AREA_UPDATING 						= 15000, 5  
	TRACKING_AREA_UPDATING_ACCEPT				= 6000,  5
	DEFAULT_EPS_BEARER_CONTEXT_ACTIVATION 		= 8000,  5  
	DEDICATED_EPS_BEARER_CONTEXT_ACTIVATION		= 8000,  5  
	UE_REQUESTED_BEARER_RESOURCE_ALLOCATION 	= 8000,  5  
	UE_REQUESTED_BEARER_RESOURCE_MODIFICATION 	= 8000,  5  
	EPS_BEARER_CONTEXT_DEACTIVATION				= 8000,  5  
	EPS_BEARER_CONTEXT_MODIFICATION 			= 8000,  5  
	UE_REQUESTED_PDN_CONNECTIVITY 				= 8000,  5  
	UE_REQUESTED_PDN_DISCONNECT 				= 6000,  5  
	PAGING                                      = 3000,  5

	SGs_CSFB_MT									= 20000, 2
	SGs_SMS_MT									= 20000, 2
	SGs_SMS_MO									= 20000, 2
	SGs_LOCATION_UPDATE							= 90000, 2
	SGs_EPS_DETACH								= 30000, 2
	SGs_IMSI_DETACH								= 30000, 2
	SGs_ALERT									= 30000, 2
	SGs_RESET									= 120000,2

	CSFB_MTC_CONNECTED							= 90000, 2
	CSFB_MOC_CONNECTED							= 90000, 2
	CSFB_MTC_FALLBACK							= 90000, 2
	CSFB_MOC_FALLBACK							= 90000, 2
	CSFB_MOCMTC_RETURN							= 90000, 2
	CSFB_SGS_PAGING								= 20000, 2
	CSFB_NAS_COMBINE_TAU						= 21000, 5
	CSFB_NAS_COMBINE_ATTACH						= 21000, 5

# Configure the input data streams below
#################################################################
[DataStreams]
	# The selected stream list, which are configured in section [DataStream#] below
	EnabledStream =PCAP_File
	
	# Max allowed delay for each stream, in seconds
	# if no data is received for a stream more than [AllowedMaxStreamDelay] seconds, the stream is treat as INACTIVE, until new data is received.
	AllowedMaxStreamDelay = 60
	TimeZone = +8
	
# Configure each DataStream. If the stream is not selected in the EnabledStream list, it will not take effect.

[PCAP_File]
	# Stream type, PCAP_FILE or PCAP_IF or QCAP_IF
	Type =PCAP_FILE
	
	#offline or online, default online
	#offline: exit after decoding
	#online:run all the time
	WorkMode=offline

	# Data input directory
	Directory =D:\Project\Decoder\decode6\新建 文件夹\TMP_12345\
	
	# The prefix and suffix of the file name to identify this stream
	FileNamePrefix =
	FileNameSuffix =
	
	# The max value for the input file name loop
	MaxFileNameIdx = 999999999
	
	# 0 or 1; 0:move;	1:delete;
	MoveOrDelete =0
	RemoveDirectory =D:\Project\Decoder\decode6\新建 文件夹\Keep\  

[PCAP_Stream1]
	# Stream type, PCAP_FILE or PCAP_IF or QCAP_IF or NTCI_IF
	Type =PCAP_IF
	RulePort =
	IpAddress =  
	ForceCPU0 = FALSE

[PCAP_Stream2]
	# Stream type, PCAP_FILE or PCAP_IF or QCAP_IF or NTCI_IF
	Type = NTCI_IF
	FilterRule = D:\EasyAnalyzer\bin\cfg\filter_rule.ini
	RulePort = 
	IpAddress = 
	ForceCPU0 = FALSE
	
[PCAP_Stream3]
	# Stream type, PCAP_FILE or PCAP_IF or QCAP_IF or NTCI_IF
	Type = PCAP_IF
	RulePort = 
    IpAddress = 
	ForceCPU0 = FALSE

[PCAP_Stream4]
	# Stream type, PCAP_FILE or PCAP_IF or QCAP_IF or NTCI_IF
	Type = PCAP_IF
	RulePort = 
	IpAddress = 
	ForceCPU0 = FALSE

[FlowControl]
	#Support flow control enable, TRUE or FALSE
	FlowEnable = FALSE

	#1:if match then process else drop for cp and up; 2:if match then drop else process for cp and up; 
	#3:if match then process else drop for only up; 4:if match then drop else process for only up; 
	FlowMode = 3

	#IPRule-n = 10.139.1.141
	#for example: IPRule_1 = 10.139.1.141
	#for example: IPRule_2 = 10.139.1.143-10.139.1.145
	#IPRule_1 = 10.139.1.141

[TOPO_NODE_MME]
	#MMEIP_1 = 10.220.115.42 
	#MMEIP_2 = 10.220.115.99

[TOPO_NODE_SGW]	
	#SGWIP_1 = 10.220.115.42 
	#SGWIP_2 = 10.220.115.99

[TOPO_NODE_SGWU]
	#SGWIP_1 = 100.80.254.129 
	#SGWIP_2 = 100.80.254.130

[TOPO_NODE_HSGW]
	#HSGWIP_1 = 115.169.138.123
	#HSGWIP_2 = 115.169.138.123

[TOPO_NODE_HPGW]
	#HPGWIP_1 = 115.169.138.150
	#HPGWIP_2 = 115.169.138.151
